private_gsheets_url = "https://docs.google.com/spreadsheets/d/1mKfzM-OLuNtyTav5MMHtvXFzAwDu0L0mSqiYDv11Ay0/edit#gid=1543864565"

[login]
LOGIN_PASSWORD = "durian2023!"


[gcp_service_account]
type = "service_account"
project_id = "er-2023"
private_key_id = "4c18f93e62afb3eb2ec7baa6cde9887c9eee08a9"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCH3GF7eqOcYQKH\nrCMGVVpUbYg/yFimYJQhCXc6AIXcmdWBDMkGGYp4g3r/8LR3CkCmx5f1w9Fzb28Z\n4izkldnLPFaUY8tfUV/k1jkeiEm6QvTz3lXHrDFQ566wwGxi6wF4iSQS5KrBcJDF\nUuUlCmfzfcYxh1XUAHombZwB2lt3+/YaA9WA2VtgPVeX8tATei3fso6dYozq4G32\nsGKWNYN+azBEQznG0CkvBLWPDrXXJe8n53n0X97QRBjcPyCqjW18bp5ht6loPcSH\ni0j3tru/bVcGKe33D98c3LLXm6vfyi+3ROATg84KDvM5U4Eilyjm8LupzPF/HyKZ\nr8yjkfh3AgMBAAECggEAD4o0IO5oAhjl3q81pGGlPuH2bdaUg+ypFNb4gGBomfvY\nkXXCapmySSg/ges+NnLW7pyxiNFt8YZjTrJxpcXEJHx8KhCjcFLQ+qOhje39148V\nZe2I90P+shKGBz6YnH86laxuErZ9bOSGEqPxhNlEsZ5cdJ7Wa4o7GTkmromTi8zR\n8VMFyJfOoBFs4TyUgLPwtWFOqSCQfXC4jInHNMIcFdikCydv6F1Oj4H3ftCriuF1\n1snkujAujUxth7m9Vm9rXufDWQEAivsVtwM/ourfcqH6lBi55ZgllRDPGU9tnUK9\n4Ea5D/vayJ5V7C53t9NzFtMcgK9HU4kwulsBV8ULuQKBgQC7fxqg4sV6PQ/obTC3\nLVG+o13d8sOwEI9q+IX+7dRTs2wec8P8swVop7+woRgxanJOhBZMQHC4ZgPWgyH5\ntHjazq4fIvK011qSI+/BTIUHAeM/hQlbecZAUqkmtE1fzXk9hM1frgUmQZ85z3u7\n3uc2u6Do7U7H8++wqr8wY6eIDwKBgQC5f7Mc2axiO02j5WBlIv/gtqcYNU4O1RKi\nuWuWECRHReuLd3AordJhsq+KiO2KXXhnDCgqbWMvrR/oOvX9jw+5d/cvxGacuCad\nfQLjToOpP5rurLAC7mqQZkBcFuE18l+AQ4h64TbpnAlMiNJFIFXjNpGr+2xRcCpx\nv+l3T9hhGQKBgAzh+9toGXd/sJMgxYMgiwhVQ0LXxlhXmvMXpmVQxBEIN/qTq7i2\nOD3roMErIHVswfPhIYMVvmj9IXBgzDnTC6bFIrOi/Bgu39tAut2GO3Gy0IFxy6XM\nZTHQPC0boGFfxd/TOyVC2Lm7MoyPVAohk7NwCutWOt6ERUjXQpG5ly5DAoGAfDsk\nxpaVV3hmB/TPeQxWl7Vb9N+GNnLGt0o83lRTJ5SRKmdEK0o2Uo3r+Hi5tWfiAgln\nQPrfaYeljc8m/bh5DHpmhowfOKgv3Ftjur3TeV8KsPvgKSZpIeoJAmOkUo/PG8Se\nu8TnFM8WfzZGtFryimf6aVbJ9USMeH/RqMFFpckCgYEAmfbhWOjFGri4ww+yZbbU\noQho+N97SfxBHXAdzjI9OTmMAadVVT4oQPmFqHTsLErfYEb4LnYr79T+dY0XWXGA\n67yMuCt0i/f5rvLIp8KPVPvqe/CudgpR1M1VeS+fKhxqs7gfOixhvdCie7kYI2E4\ncRi611zO0UNEMFbxlowJ8q4=\n-----END PRIVATE KEY-----\n"
client_email = "service-acc@er-2023.iam.gserviceaccount.com"
client_id = "100622528393959743857"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/service-acc%40er-2023.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[spreadsheet]
SPREADSHEET_ID = "1mKfzM-OLuNtyTav5MMHtvXFzAwDu0L0mSqiYDv11Ay0"
